inherit: true

build:
  image: default-bionic
  environment:
    php: 8.3.22
  nodes:
    analysis:
      tests:
        override: [php-scrutinizer-run]

checks:
  php:
    code_rating: true
    duplication: true

filter:
  paths: [code/*, tests/*]
