mappings:
  DebugBarDatabaseCollector: LeKoala\DebugBar\Collector\DatabaseCollector
  DebugBarSilverStripeCollector: LeKoala\DebugBar\Collector\SilverStripeCollector
  DebugBarTimeDataCollector: LeKoala\DebugBar\Collector\TimeDataCollector
  DebugBarControllerExtension: LeKoala\DebugBar\Extension\ControllerExtension
  DebugBarLeftAndMainExtension: LeKoala\DebugBar\Extension\LeftAndMainExtension
  DebugBarTemplateParserProxy: LeKoala\DebugBar\Proxy\TemplateParserProxy
  DebugBarController: LeKoala\DebugBar\DebugBarController
  DebugBar: LeKoala\DebugBar\DebugBar
  DebugBarRequestFilter: LeKoala\DebugBar\RequestFilter
  DebugBarControllerTest: LeKoala\DebugBar\Test\ControllerTest
  DebugBarDebugBarTest: LeKoala\DebugBar\Test\DebugBarTest
  DebugBarDatabaseCollectorTest: LeKoala\DebugBar\Test\Collector\DatabaseCollectorTest
  DebugBarSilverStripeCollectorTest: LeKoala\DebugBar\Test\Collector\SilverStripeCollectorTest
  DebugBarTimeDataCollectorTest: LeKoala\DebugBar\Test\Collector\TimeDataCollectorTest
  DebugBarControllerExtensionTest: LeKoala\DebugBar\Test\Extension\ControllerExtensionTest
  DebugBarLeftAndMainExtensionTest: LeKoala\DebugBar\Test\Extension\LeftAndMainExtensionTest
  DebugBarTemplateParserProxyTest: LeKoala\DebugBar\Test\Proxy\TemplateParserProxyTest
